# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.0
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: daniel.mcgregor@makerx.com.au
author_name: Daniel McGregor
deployment_language: typescript
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: typed-client-examples
python_linter: ruff
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: false
use_python_pytest: true

