import * as algokit from '@algorandfoundation/algokit-utils'
import { DecIndent, DecIndentAndCloseBlock, DocumentParts, IncIndent, indent, inline, NewLine } from '../output/writer'
import {
  isSafeVariableIdentifier,
  makeSafeMethodIdentifier,
  makeSafePropertyIdentifier,
  makeSafeTypeIdentifier,
  makeSafeVariableIdentifier,
} from '../sanitization'
import { AlgoAppSpec, ContractMethod } from '../schema/application'

export function* generateClient(app: AlgoAppSpec): DocumentParts {
  yield `/* eslint-disable */`
  yield `/**`
  yield ` * This file was automatically generated by algokit-client-generator.`
  yield ` * DO NOT MODIFY IT BY HAND.`
  yield ` */`

  yield* imports()
  yield* inline('export const APP_SPEC: AppSpec = ', JSON.stringify(app, undefined, 2))
  yield NewLine

  yield* utilityTypes()
  yield NewLine

  for (const method of app.contract.methods) {
    yield* argTypes(method)
  }
  yield NewLine
  yield* deployTypes(app)

  // Write a call factory
  yield* callFactory(app)
  yield NewLine
  // Write a client
  yield* client(app)
}
function* deployTypes(app: AlgoAppSpec): DocumentParts {
  const name = makeSafeTypeIdentifier(app.contract.name)
  yield `export type ${name}CreateArgs = BareCallArgs`
  yield `export type ${name}UpdateArgs = BareCallArgs`
  yield `export type ${name}DeleteArgs = BareCallArgs`
  yield `export type ${name}DeployArgs = {`
  yield IncIndent
  yield `deployTimeParams?: TealTemplateParams`
  yield `createArgs?: ${name}CreateArgs & CoreAppCallArgs`
  yield `updateArgs?: ${name}UpdateArgs & CoreAppCallArgs`
  yield `deleteArgs?: ${name}DeleteArgs & CoreAppCallArgs`
  yield DecIndentAndCloseBlock
  yield NewLine
}

function* client(app: AlgoAppSpec): DocumentParts {
  yield `/** A client to make calls to the ${app.contract.name} smart contract */`
  yield `export class ${makeSafeTypeIdentifier(app.contract.name)}Client {`
  yield IncIndent
  yield '/** The underlying `ApplicationClient` for when you want to have more flexibility */'
  yield 'public readonly appClient: ApplicationClient'
  yield NewLine
  yield '/**'
  yield ` * Creates a new instance of \`${makeSafeTypeIdentifier(app.contract.name)}Client\``
  yield ' * @param appDetails The details to identify the app to deploy'
  yield ' * @param algod An algod client instance'
  yield ' */'
  yield `constructor(appDetails: AppDetails, algod: Algodv2) {`
  yield IncIndent
  yield 'this.appClient = algokit.getAppClient({'
  yield* indent('...appDetails,', 'app: APP_SPEC')
  yield '}, algod)'
  yield DecIndent
  yield '}'
  yield NewLine
  yield* genericCallMethod()
  yield* deployMethods(app)
  yield* clientCallMethods(app)
  yield DecIndentAndCloseBlock
}

function* deployMethods(app: AlgoAppSpec): DocumentParts {
  const name = makeSafeTypeIdentifier(app.contract.name)
  yield `/**`
  yield ` * Idempotently deploys the ${app.contract.name} smart contract.`
  yield ` * @param params The arguments for the contract calls and any additional parameters for the call`
  yield ` * @returns The deployment result`
  yield ` */`
  yield `public deploy(params: ${name}DeployArgs & AppClientDeployCoreParams = {}) {`
  yield IncIndent
  yield `return this.appClient.deploy({ ...params, })`
  yield DecIndentAndCloseBlock
  yield NewLine

  yield `/**`
  yield ` * Creates a new instance of the ${app.contract.name} smart contract.`
  yield ` * @param args The arguments for the contract call`
  yield ` * @param params Any additional parameters for the call`
  yield ` * @returns The creation result`
  yield ` */`
  yield `public create(args: ${name}CreateArgs = {}, params?: AppClientCallCoreParams & AppClientCompilationParams & CoreAppCallArgs) {`
  yield IncIndent
  yield `return this.appClient.create({ ...args, ...params, })`
  yield DecIndentAndCloseBlock
  yield NewLine

  yield `/**`
  yield ` * Updates an existing instance of the ${app.contract.name} smart contract.`
  yield ` * @param args The arguments for the contract call`
  yield ` * @param params Any additional parameters for the call`
  yield ` * @returns The update result`
  yield ` */`
  yield `public update(args: ${name}UpdateArgs = {}, params?: AppClientCallCoreParams & AppClientCompilationParams & CoreAppCallArgs) {`
  yield IncIndent
  yield `return this.appClient.update({ ...args, ...params, })`
  yield DecIndentAndCloseBlock
  yield NewLine

  yield `/**`
  yield ` * Deletes an existing instance of the ${app.contract.name} smart contract.`
  yield ` * @param args The arguments for the contract call`
  yield ` * @param params Any additional parameters for the call`
  yield ` * @returns The deletion result`
  yield ` */`
  yield `public delete(args: ${name}DeleteArgs = {}, params?: AppClientCallCoreParams & AppClientCompilationParams & CoreAppCallArgs) {`
  yield IncIndent
  yield `return this.appClient.delete({ ...args, ...params, })`
  yield DecIndentAndCloseBlock
  yield NewLine
}

function* genericCallMethod(): DocumentParts {
  yield 'public async call<TReturn>(params: CallRequest<TReturn, any>): Promise<AppCallTransactionResultOfType<TReturn>> {'
  yield IncIndent
  yield `const result = await this.appClient.call(params)`
  yield `if(result.return?.decodeError) {`
  yield* indent(`throw result.return.decodeError`)
  yield '}'
  yield 'const returnValue = result.return?.returnValue as TReturn'
  yield 'return { ...result, return: returnValue }'
  yield DecIndentAndCloseBlock
  yield NewLine
}

function* clientCallMethods(app: AlgoAppSpec): DocumentParts {
  for (const method of app.contract.methods) {
    yield `/**`
    if (method.desc) {
      yield ` * ${method.desc}`
      yield ` *`
    }
    yield ` * Calls the ${algokit.getABIMethodSignature(method)} ABI method.`
    yield ` *`
    yield ` * @param args The arguments for the ABI method`
    yield ` * @param params Any additional parameters for the call`
    yield ` * @returns The result of the call`
    yield ` */`
    yield `public ${makeSafeMethodIdentifier(method.name)}(args: ${makeSafeTypeIdentifier(
      method.name,
    )}Args, params?: AppClientCallCoreParams & CoreAppCallArgs) {`
    yield IncIndent
    yield `return this.call(${makeSafeTypeIdentifier(app.contract.name)}CallFactory.${makeSafeMethodIdentifier(method.name)}(args, params))`
    yield DecIndent
    yield '}'
    yield NewLine
  }
}

function* argTypes({ name, args }: ContractMethod): DocumentParts {
  const safeIdentifier = makeSafeTypeIdentifier(name)
  yield `export type ${safeIdentifier}ArgsObj = {`
  yield IncIndent
  for (const arg of args) {
    yield `'${makeSafePropertyIdentifier(arg.name)}': ${arg.type}`
  }
  yield DecIndent
  yield '}'
  yield* inline(
    `export type ${safeIdentifier}ArgsTuple = [`,
    args.map((t) => `${makeSafeVariableIdentifier(t.name)}: ${t.type}`).join(','),
    ']',
  )
  yield `export type ${safeIdentifier}Args = ${safeIdentifier}ArgsObj | ${safeIdentifier}ArgsTuple`
}

function* callFactory(app: AlgoAppSpec): DocumentParts {
  yield `export abstract class ${makeSafeTypeIdentifier(app.contract.name)}CallFactory {`
  yield IncIndent
  for (const method of app.contract.methods) {
    yield* callFactoryMethod(method)
  }
  yield DecIndent
  yield '}'
}

function* callFactoryMethod(method: ContractMethod) {
  yield `static ${makeSafeMethodIdentifier(method.name)}(args: ${makeSafeTypeIdentifier(
    method.name,
  )}Args, params: AppClientCallCoreParams & CoreAppCallArgs = {}): CallRequest<${method.returns?.type ?? 'void'}, ${makeSafeTypeIdentifier(
    method.name,
  )}ArgsTuple>  {`
  yield IncIndent
  yield `return {`
  yield IncIndent
  yield `method: '${algokit.getABIMethodSignature(method)}',`
  yield `methodArgs: Array.isArray(args) ? args : [${method.args
    .map((a) => (isSafeVariableIdentifier(a.name) ? `args.${a.name}` : `args['${makeSafePropertyIdentifier(a.name)}']`))
    .join(',')}],`
  yield '...params,'
  yield DecIndent
  yield '}'
  yield DecIndent
  yield '}'
}

function* utilityTypes(): DocumentParts {
  yield 'export type CallRequest<TReturn, TArgs = undefined> = {'
  yield IncIndent
  yield 'method: string'
  yield 'methodArgs: TArgs'
  yield DecIndent
  yield '} & AppClientCallCoreParams & CoreAppCallArgs'

  yield `export type BareCallArgs = Omit<RawAppCallArgs, keyof CoreAppCallArgs>`
}

function* imports(): DocumentParts {
  yield `import * as algokit from '@algorandfoundation/algokit-utils'
import {
  AppCallTransactionResultOfType,
  CoreAppCallArgs,
  RawAppCallArgs,
  TealTemplateParams,
} from '@algorandfoundation/algokit-utils/types/app'
import {
  AppClientCallCoreParams,
  AppClientCompilationParams,
  AppClientDeployCoreParams,
  AppDetails,
  ApplicationClient,
} from '@algorandfoundation/algokit-utils/types/app-client'
import { AppSpec } from '@algorandfoundation/algokit-utils/types/app-spec'
import { Algodv2 } from 'algosdk'`
}
